#!/usr/bin/env bash
#
# Exercises the SSH engine against a real OpenSSH server.
#
# SSHBondSession is deliberately free of Android and Expo dependencies so the
# part that is genuinely hard to get right -- the handshake, host key gating,
# PTY allocation and stream lifetime -- can be verified on a plain JVM instead
# of only inside an emulator.
#
# It starts a throwaway sshd on 127.0.0.1:2222, authenticates with a key
# generated by SSHBond's own key manager, and asserts on the events the engine
# emits -- including that -L, -R and -D really carry bytes.
#
# Requirements: JDK 17+, kotlinc, ssh-keygen, sshd, and network access to Maven
# Central on first run.
#
# Usage: modules/expo-sshbond/integration/run.sh

set -euo pipefail

MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$MODULE_DIR/../.." && pwd)"
WORK_DIR="${TMPDIR:-/tmp}/sshbond-engine-it"
JSCH_VERSION="2.28.7"

RED=$'\e[31m'; GREEN=$'\e[32m'; DIM=$'\e[2m'; RESET=$'\e[0m'

log() { echo "${DIM}==>${RESET} $*"; }
die() { echo "${RED}error:${RESET} $*" >&2; exit 1; }

for tool in java kotlinc ssh-keygen curl; do
  command -v "$tool" >/dev/null || die "$tool is required but not on PATH"
done

SSHD_BIN="$(command -v sshd || echo /usr/sbin/sshd)"
[ -x "$SSHD_BIN" ] || die "sshd is required but was not found"

mkdir -p "$WORK_DIR"
SSHD_DIR="$WORK_DIR/sshd"
rm -rf "$SSHD_DIR"
mkdir -p "$SSHD_DIR"

cleanup() {
  if [ -f "$SSHD_DIR/sshd.pid" ]; then
    kill "$(cat "$SSHD_DIR/sshd.pid")" 2>/dev/null || true
  fi
}
trap cleanup EXIT

# --- dependencies -----------------------------------------------------------
JSCH_JAR="$WORK_DIR/jsch-$JSCH_VERSION.jar"
if [ ! -f "$JSCH_JAR" ]; then
  log "downloading jsch $JSCH_VERSION"
  curl -sSL -o "$JSCH_JAR" \
    "https://repo1.maven.org/maven2/com/github/mwiede/jsch/$JSCH_VERSION/jsch-$JSCH_VERSION.jar"
fi

# --- keys -------------------------------------------------------------------
log "generating server host key"
ssh-keygen -q -t ed25519 -N '' -f "$SSHD_DIR/host_ed25519" -C 'sshbond-integration-host'
chmod 600 "$SSHD_DIR/host_ed25519"

log "generating an unauthorised key (for the rejection case)"
ssh-keygen -q -t ed25519 -N '' -f "$SSHD_DIR/bogus_key" -C 'not-authorized'

# The client key comes from SSHBond's own generator, so the run also proves the
# app produces keys OpenSSH actually accepts.
log "generating the client key with SSHBond's key manager"
GEN_TEST_DIR="$PROJECT_ROOT/test/.integration-tmp"
mkdir -p "$GEN_TEST_DIR"
cat > "$GEN_TEST_DIR/generate.test.ts" <<'TS'
import * as fs from 'fs';
import { SSHKeyManager } from '../../src/services/ssh/keys/SSHKeyManager';

it('generates the client key used by the engine integration run', async () => {
  const dir = process.env.SSHD_DIR!;
  const pair = await SSHKeyManager.generateKeyPair({
    name: 'integration',
    algorithm: 'ed25519',
    comment: 'sshbond@integration',
  });
  fs.writeFileSync(`${dir}/client_key`, `${pair.privateKey}\n`, { mode: 0o600 });
  fs.writeFileSync(`${dir}/authorized_keys`, `${pair.publicKey}\n`, { mode: 0o600 });
});
TS
(cd "$PROJECT_ROOT" && SSHD_DIR="$SSHD_DIR" npx jest "test/.integration-tmp/generate.test.ts" --silent >/dev/null 2>&1) \
  || die "could not generate the client key with SSHKeyManager"
rm -rf "$GEN_TEST_DIR"

# --- sshd -------------------------------------------------------------------
cat > "$SSHD_DIR/sshd_config" <<EOF
Port 2222
ListenAddress 127.0.0.1
HostKey $SSHD_DIR/host_ed25519
AuthorizedKeysFile $SSHD_DIR/authorized_keys
PidFile $SSHD_DIR/sshd.pid
StrictModes no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
# The forwarding checks need both directions; these are the defaults, stated
# here so a distro that ships a stricter sshd does not silently skip them.
AllowTcpForwarding yes
GatewayPorts no
UsePAM no
PrintMotd no
LogLevel VERBOSE
EOF

log "starting sshd on 127.0.0.1:2222"
"$SSHD_BIN" -f "$SSHD_DIR/sshd_config" -E "$SSHD_DIR/sshd.log" -D &
sleep 2
grep -q "Server listening" "$SSHD_DIR/sshd.log" || die "sshd failed to start; see $SSHD_DIR/sshd.log"

# --- build ------------------------------------------------------------------
log "compiling the engine"
kotlinc \
  "$MODULE_DIR/android/src/main/java/expo/modules/sshbond/SSHBondTypes.kt" \
  "$MODULE_DIR/android/src/main/java/expo/modules/sshbond/SSHBondSession.kt" \
  "$MODULE_DIR/android/src/main/java/expo/modules/sshbond/SSHPortForwards.kt" \
  -classpath "$JSCH_JAR" -d "$WORK_DIR/engine.jar" 2>&1 | grep -v '^warning:' || true

log "compiling the harness"
kotlinc "$MODULE_DIR/integration/SSHBondSessionIntegrationTest.kt" \
  -classpath "$JSCH_JAR:$WORK_DIR/engine.jar" -d "$WORK_DIR/harness.jar" 2>&1 | grep -v '^warning:' || true

KOTLIN_STDLIB="$(dirname "$(readlink -f "$(command -v kotlinc)")")/../lib/kotlin-stdlib.jar"

# --- run --------------------------------------------------------------------
FINGERPRINT="$(ssh-keygen -lf "$SSHD_DIR/host_ed25519.pub" | awk '{print $2}')"
log "expected host key fingerprint: $FINGERPRINT"

if java -cp "$WORK_DIR/harness.jar:$WORK_DIR/engine.jar:$JSCH_JAR:$KOTLIN_STDLIB" \
     SSHBondEngineIntegration "$SSHD_DIR" "$FINGERPRINT"; then
  echo "${GREEN}engine integration: OK${RESET}"
else
  die "engine integration failed (sshd log: $SSHD_DIR/sshd.log)"
fi
